"""initial schema

Revision ID: 99843e993371
Revises:
Create Date: 2026-10-03 14:32:59.345749

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99843e993371'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('quota_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quota_used_bytes >= 0', name='ck_user_quota_used_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('allowed_emails',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('invited_by', sa.String(length=255), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'PROJECT_CREATE', 'PROJECT_DELETE', 'PROJECT_SHARE', 'PROJECT_UNSHARE', 'FILE_UPLOAD', 'FILE_DELETE', 'COMPILE_START', 'COMPILE_COMPLETE', name='audit_action'), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_log_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_log_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_compiled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('size_bytes >= 0', name='ck_project_size_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_project_owner', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_project_owner_updated', 'projects', ['owner_id', 'updated_at'], unique=False)
    op.create_table('compile_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'COMPILING', 'COMPLETED', 'FAILED', 'TIMEOUT', name='compile_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('compile_time', sa.Float(), nullable=True),
    sa.Column('pdf_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('log_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compile_job_created_at', 'compile_jobs', ['created_at'], unique=False)
    op.create_index('idx_compile_job_project', 'compile_jobs', ['project_id'], unique=False)
    op.create_index('idx_compile_job_status', 'compile_jobs', ['status'], unique=False)
    op.create_index('idx_compile_job_user', 'compile_jobs', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('yjs_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_file_size_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'path', name='uq_project_file')
    )
    op.create_index('idx_file_hash', 'files', ['hash'], unique=False)
    op.create_index('idx_file_project', 'files', ['project_id'], unique=False)
    op.create_index('idx_file_project_path', 'files', ['project_id', 'path'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='project_role'), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index('idx_project_member_project', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_member_user', 'project_members', ['user_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_created_at', 'snapshots', ['created_at'], unique=False)
    op.create_index('idx_snapshot_project', 'snapshots', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshot_project', table_name='snapshots')
    op.drop_index('idx_snapshot_created_at', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index('idx_project_member_user', table_name='project_members')
    op.drop_index('idx_project_member_project', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_file_project_path', table_name='files')
    op.drop_index('idx_file_project', table_name='files')
    op.drop_index('idx_file_hash', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_compile_job_user', table_name='compile_jobs')
    op.drop_index('idx_compile_job_status', table_name='compile_jobs')
    op.drop_index('idx_compile_job_project', table_name='compile_jobs')
    op.drop_index('idx_compile_job_created_at', table_name='compile_jobs')
    op.drop_table('compile_jobs')
    op.drop_index('idx_project_owner_updated', table_name='projects')
    op.drop_index('idx_project_owner', table_name='projects')
    op.drop_index('idx_project_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('idx_audit_log_user', table_name='audit_logs')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_log_resource', table_name='audit_logs')
    op.drop_index('idx_audit_log_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('allowed_emails')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
